name: all_url_check

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '25 */3 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Link Checker
      uses: lycheeverse/lychee-action@v1.0.8
      with:
        args: --verbose --insecure --no-progress **/*.tex **/*.md
