---
name: all_url_check

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '25 */3 * * *'

jobs:
  run_lychee:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: link_check with lychee-action
        id: link_check
        uses: lycheeverse/lychee-action@v1.4.1
        with:
          args: >
            --verbose
            --insecure
            --no-progress
            --timeout 10
            **/*.tex **/*.md

      - name: Fail if there were link errors
        run: exit ${{steps.link_check.outputs.exit_code}}
...
