name: build_document

on:
  push:
    paths-ignore:
      - 'generated/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get install texlive-latex-base
        sudo apt-get install texlive-fonts-recommended
        tlmgr install datetime
        tlmgr install xcolor
        tlmgr install nth

    - name: Build
      shell: bash
      run: pdflatex academic_activities_eng.tex
