name: build_document

on:
  push:
    paths-ignore:
      - 'generated/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get install texlive-latex-extra
        #sudo apt-get install texlive-fonts-recommended
    #- name: Install dependencies
    #  run: |
    #    tlmgr init-usertree
    #    tlmgr install datetime
    #    tlmgr install xcolor
    #    tlmgr install nth

    - name: Build
      shell: bash
      run: | 
        for run_num in {1..3}; do pdflatex academic_activities_eng.tex -output-directory=./generated; done
