---
name: latex_linter_check

'on':
  workflow_dispatch:
  push:
    paths-ignore:
      - 'generated/**'

permissions:
  contents: read

jobs:
  run_chktex:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: LaTeX linter
        uses: colinaaa/chktex-action@5dda098b973d69cdc61ace93fa7bfcef39efaade # v1.1.2
...
