name: latex_linter_check

on:
  push:
    paths-ignore:
      - 'generated/**'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: LaTeX linter
        uses: colinaaa/chktex-action@v1.1.2
